// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIlBwDDgStC1dxRrX_M5lS2WcXXTzI430',
    appId: '1:1001231000295:web:68ae30ad1e2a49b8693842',
    messagingSenderId: '1001231000295',
    projectId: 'eeshangarg-fitness-copilot',
    authDomain: 'eeshangarg-fitness-copilot.firebaseapp.com',
    storageBucket: 'eeshangarg-fitness-copilot.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkzEc0PIa8M1ijmGnVuvVuYFhFCiyKI6s',
    appId: '1:1001231000295:android:0f6a05bb25f2b0f4693842',
    messagingSenderId: '1001231000295',
    projectId: 'eeshangarg-fitness-copilot',
    storageBucket: 'eeshangarg-fitness-copilot.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxb-iQaeyxC3zsJyGSkhCKJn8rMGmNgdc',
    appId: '1:1001231000295:ios:6a09e2b6bd993c86693842',
    messagingSenderId: '1001231000295',
    projectId: 'eeshangarg-fitness-copilot',
    storageBucket: 'eeshangarg-fitness-copilot.appspot.com',
    iosClientId: '1001231000295-vve8pvnnftpo5kau0p1knj6i922dl277.apps.googleusercontent.com',
    iosBundleId: 'com.eeshangarg.fitnessCopilot',
  );
}
